spring:
    application:
        name: secuirty-demo-app

server:
    port: 8081

application:
    security:
        signin-url: http://${SECURITY_SERVER_HOST:localhost}:${SECURITY_SERVER_PORT:8080}/auth/signin
        signout-url: http://${SECURITY_SERVER_HOST:localhost}:${SECURITY_SERVER_PORT:8080}/auth/signout
        get-permission-url: http://${SECURITY_SERVER_HOST:localhost}:${SECURITY_SERVER_PORT:8080}/auth/myaccesspermission
    cors:
        allowed-origins: ALL
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS

